name: dokan
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_animate: ^4.0.0
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  get_it: ^7.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  in_app_update: null
  internet_connection_checker:
  intl: ^0.19.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  image_picker: ^0.8.7+5
  animated_bottom_navigation_bar: ^1.3.3
  expandable: ^5.0.1
  animated_digit: ^3.2.3
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - icons/
    - assets/
